const KEY="e2fit_admin_orders";const demo=[{id:1,name:"Arun Kumar",phone:"",box:"Premium Box",plan:"Monthly",delivery:"Breakfast",address:"Gandhi Park",status:"Delivered"},{id:2,name:"Priya S",phone:"",box:"Medium Box",plan:"Monthly",delivery:"Breakfast",address:"RS Puram",status:"Out for Delivery"},{id:3,name:"Karthik",phone:"",box:"Premium Pro Box",plan:"Daily",delivery:"Lunch",address:"Saibaba Colony",status:"Preparing"}];
function getOrders(){return JSON.parse(localStorage.getItem(KEY)||"null")||demo}function save(){localStorage.setItem(KEY,JSON.stringify(orders))}
let orders=getOrders();
const login=document.getElementById("login"),app=document.getElementById("app");
document.getElementById("loginBtn").onclick=()=>{if(document.getElementById("adminUser").value==="admin"&&document.getElementById("adminPass").value==="e2fit2026"){sessionStorage.e2fitAdmin="1";show()}else alert("Invalid demo login")};
function show(){login.classList.add("hidden");app.classList.remove("hidden");render()}if(sessionStorage.e2fitAdmin==="1")show();
document.getElementById("logout").onclick=()=>{sessionStorage.removeItem("e2fitAdmin");location.reload()};
function render(){const filter=document.getElementById("filter").value;const visible=filter==="All"?orders:orders.filter(o=>o.status===filter);document.getElementById("total").textContent=orders.length;document.getElementById("preparing").textContent=orders.filter(o=>o.status==="Preparing").length;document.getElementById("out").textContent=orders.filter(o=>o.status==="Out for Delivery").length;document.getElementById("delivered").textContent=orders.filter(o=>o.status==="Delivered").length;
document.getElementById("orders").innerHTML=visible.map(o=>'<div class="order"><div class="customer"><strong>'+o.name+'</strong><small>'+o.address+'</small></div><div><strong>'+o.box+'</strong><div class="muted">'+o.plan+'</div></div><div><strong>'+o.delivery+'</strong></div><div class="status-action"><span class="pill '+(o.status==="Out for Delivery"?"Out":o.status)+'">'+o.status+'</span> <button class="status-btn" onclick="advance('+o.id+')">Next →</button></div></div>').join("")||'<div style="padding:30px;color:#879189">No orders found.</div>';
document.getElementById("customerRows").innerHTML=orders.map(o=>'<tr><td><strong>'+o.name+'</strong></td><td>'+o.box+'</td><td>'+o.plan+'</td><td>'+o.delivery+'</td><td><span class="pill '+(o.status==="Out for Delivery"?"Out":o.status)+'">'+o.status+'</span></td></tr>').join("")}
function advance(id){const sequence=["Pending","Preparing","Out for Delivery","Delivered"];const o=orders.find(x=>x.id===id);const i=sequence.indexOf(o.status);if(i<sequence.length-1)o.status=sequence[i+1];save();render()}
document.getElementById("filter").onchange=render;
const modal=document.getElementById("orderModal");document.getElementById("newOrder").onclick=()=>modal.classList.remove("hidden");document.getElementById("closeModal").onclick=()=>modal.classList.add("hidden");
document.getElementById("saveOrder").onclick=()=>{const o={id:Date.now(),name:document.getElementById("name").value||"New Customer",phone:document.getElementById("phone").value,box:document.getElementById("box").value,plan:document.getElementById("plan").value,delivery:document.getElementById("delivery").value,address:document.getElementById("address").value||"Address pending",status:"Pending"};orders.unshift(o);save();modal.classList.add("hidden");render();document.querySelectorAll("#orderModal input").forEach(i=>i.value="")};